# Generated by Django 4.2 on 2023-04-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Al_Khalil', '0002_book_tasbih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='book'),
        ),
        migrations.AlterField(
            model_name='tasbih',
            name='photo',
            field=models.ImageField(upload_to='tasbih'),
        ),
    ]
